### ISSUE TITLE
Ensure Erlang posts from stratus3d.com are listed

### ISSUE THREAD

**Issue by Stratus3D** [stevenproctor/planet-erlang#11]
No blog posts from stratus3d.com are shown on the planeterlang.com homepage. The URL checked into the repository is correct (http://stratus3d.com/blog/categories/erlang/atom.xml). I haven't made any changes to the architecture of stratus3d.com and it should be working as it has been. It's a static site, so the atom feed only gets re-generated when I deploy.

**Comment by stevenproctor** [comment]
From the server it "looks" to be working as well.  Not sure if it was that it just got missed by the PlanetErlang twitter setup for processing the feed to create tweets, or if it is not getting processed.

```
INFO:planet.runner:Updating feed http://stratus3d.com/blog/categories/erlang/atom.xml
```

If you push a new Erlang tagged post, can you ping me and I will check to make sure it is coming through after you post it.  As it only puts the last 7 days on the main page it makes it tricky to troubleshoot at this point if something is going wrong.

**Comment by Stratus3D** [comment]
My bad. It did work, but the date used in the atom feed was the date I created the markdown document, which was over a month ago. That must explain why it didn't get picked up. PlanetErlang saw it as an old post.
